[versions]
agp = "7.1.0-alpha11"
lifecycle = "2.4.0-alpha02"

[libraries]
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }