name: Build & Test

on:
  pull_request:
    branches: [ master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}
  ASOFT_NEXUS_PASSWORD: ${{ secrets.ASOFT_NEXUS_PASSWORD }}
  ASOFT_NEXUS_USERNAME: ${{ secrets.ASOFT_NEXUS_USERNAME }}

jobs:
  publish-artifacts:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/gradle-wrapper.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-
          restore-keys: ${{ runner.os }}-konan-

      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: ./build/js/node_modules
          key: ${{ runner.os }}-node-modules-
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Making gradlew executable
        run: chmod +x ./gradlew

      - name: Warm up the jvm
        run: ./gradlew tasks

      - name: Building project
        run: ./gradlew build

      - name: Publishing artifacts to sonatype
        run: ./gradlew publishToSonatype closeAndReleaseStagingRepository

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./gradlew createRelease
